package com.kyvo.app.core.navigation

enum class FoodSelectionContext { NORMAL_MEAL_LOGGING, MEAL_SHARE }

enum class KyvoDestination(val route: String) {
    Foundation("foundation"),
    Login("login"),
    Onboarding("onboarding"),
    OnboardingEdit("onboarding/edit"),
    Home("home"),
    Meals("meals"),
    Plan("plan"),
    MealShare("meal_share"),
    Progress("progress"),
    ProgressCalories("progress/calories"),
    ProgressProtein("progress/protein"),
    ProgressConsistency("progress/consistency"),
    ProgressHistory("progress/history"),
    ProgressDay("progress/day/{date}"),
    Profile("profile"),
    ProfileEdit("profile/edit"),
    ProfileNutritionPlan("profile/nutrition-plan"),
    ProfileCalculation("profile/nutrition-plan/calculation"),
    Settings("profile/settings"),
    NotificationCenter("profile/notifications"),
    Account("profile/settings/account"),
    SettingsSecurity("profile/settings/security"),
    SettingsNutritionGoals("profile/settings/nutrition-goals"),
    SettingsFoodPreferences("profile/settings/food-preferences"),
    SettingsUnits("profile/settings/units"),
    SettingsNotifications("profile/settings/notifications"),
    SettingsAppearance("profile/settings/appearance"),
    SettingsMealShare("profile/settings/meal-share"),
    SettingsPrivacy("profile/settings/privacy"),
    SettingsPermissions("profile/settings/permissions"),
    SettingsDeleteAccount("profile/settings/delete-account"),
    SettingsHelp("profile/settings/help"),
    SettingsAbout("profile/settings/about"),
    SettingsLegal("profile/settings/legal"),
    SettingsTerms("profile/settings/legal/terms"),
    SettingsNutritionNotice("profile/settings/legal/nutrition-notice"),
    SettingsLicenses("profile/settings/legal/licenses"),
    PersonalPreferences("profile/personal-preferences"),
    PersonalData("profile/personal-data"),
    ActivityTraining("profile/activity-training"),
    Experience("profile/experience"),
    FoodPreferences("profile/food-preferences"),
    MealOrganization("profile/meal-organization"),
    ReviewGoalUpdates("profile/review-goal-updates"),
    PersonalPreferencesConfirmation("profile/personal-preferences-confirmation"),
    FoodHub("food/hub"),
    FoodSearch("food/search?selectionContext={selectionContext}"),
    FoodFrequent("food/frequent"),
    FoodFavorites("food/favorites"),
    FoodResults("food/results/{query}?selectionContext={selectionContext}"),
    FoodDetail("food/detail/{id}/{type}?selectionContext={selectionContext}"),
    FoodPortion("food/portion/{id}/{type}?selectionContext={selectionContext}"),
    FoodPlaceholder("food/placeholder/{name}"),
    SavedDishes("dishes"),
    SavedDishEditor("dishes/editor/{id}"),
    SavedDishDetail("dishes/detail/{id}"),
    SavedDishAddToDay("dishes/add/{id}"),
    MealShareCamera("meal_share/camera"),
    MealSharePhotoPicker("meal_share/photo_picker"),
    MealSharePhotoPreview("meal_share/photo_preview"),
    MealShareMealBuilder("meal_share/meal_builder"),
    MealShareFoodSearchPlaceholder("meal_share/add_food"),
    MealShareEditor("meal_share/editor"),
}

val mainDestinations = listOf(
    KyvoDestination.Home,
    KyvoDestination.Meals,
    KyvoDestination.Plan,
    KyvoDestination.Progress,
    KyvoDestination.Profile,
)
