package com.kyvo.app.core.navigation

enum class FoodSelectionContext { NORMAL_MEAL_LOGGING, MEAL_SHARE }

enum class KyvoDestination(val route: String) {
    Foundation("foundation"),
    Login("login"),
    Onboarding("onboarding"),
    Home("home"),
    Meals("meals"),
    MealShare("meal_share"),
    Progress("progress"),
    ProgressCalories("progress/calories"),
    ProgressProtein("progress/protein"),
    ProgressConsistency("progress/consistency"),
    ProgressHistory("progress/history"),
    ProgressDay("progress/day/{date}"),
    Profile("profile"),
    ProfileEdit("profile/edit"),
    ProfileNutritionPlan("profile/nutrition-plan"),
    ProfileCalculation("profile/nutrition-plan/calculation"),
    ProfileUpdateGoal("profile/update-goal"),
    ProfileRecalculateGoals("profile/recalculate-goals"),
    ProfileNewGoals("profile/new-goals"),
    FoodHub("food/hub"),
    FoodSearch("food/search?selectionContext={selectionContext}"),
    FoodFrequent("food/frequent"),
    FoodFavorites("food/favorites"),
    FoodResults("food/results/{query}?selectionContext={selectionContext}"),
    FoodDetail("food/detail/{id}/{type}?selectionContext={selectionContext}"),
    FoodPortion("food/portion/{id}/{type}?selectionContext={selectionContext}"),
    FoodPlaceholder("food/placeholder/{name}"),
    SavedDishes("dishes"),
    SavedDishEditor("dishes/editor/{id}"),
    SavedDishDetail("dishes/detail/{id}"),
    SavedDishAddToDay("dishes/add/{id}"),
    MealShareCamera("meal_share/camera"),
    MealSharePhotoPicker("meal_share/photo_picker"),
    MealSharePhotoPreview("meal_share/photo_preview"),
    MealShareMealBuilder("meal_share/meal_builder"),
    MealShareFoodSearchPlaceholder("meal_share/add_food"),
    MealShareEditor("meal_share/editor"),
}

val mainDestinations = listOf(
    KyvoDestination.Home,
    KyvoDestination.Meals,
    KyvoDestination.MealShare,
    KyvoDestination.Progress,
    KyvoDestination.Profile,
)
