import { canonicalFor, gramsServing, numberOrNull, type NormalizedFood, type Nutrients } from "./food.ts";

const emptyNutrients = (): Nutrients => ({ caloriesPer100g: null, proteinPer100g: null, carbohydratesPer100g: null, fatPer100g: null, fiberPer100g: null, sugarPer100g: null, sodiumMgPer100g: null });
export async function searchUsda(query: string): Promise<NormalizedFood[]> {
  const apiKey = Deno.env.get("USDA_API_KEY"); if (!apiKey) throw new Error("USDA_API_KEY is not configured");
  const canonical = canonicalFor(query);
  const response = await fetch(`https://api.nal.usda.gov/fdc/v1/foods/search?api_key=${encodeURIComponent(apiKey)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ query: canonical?.usdaQuery ?? query, pageSize: 10, dataType: ["Foundation", "SR Legacy", "Survey (FNDDS)"] }) });
  if (!response.ok) throw new Error(`USDA search failed with ${response.status}`);
  const payload = await response.json() as { foods?: UsdaFood[] };
  return (payload.foods ?? []).map((food) => ({ type: "generic", source: "usda", sourceId: String(food.fdcId), name: canonical?.canonical ?? food.description, nameOriginal: food.description, canonicalNameEs: canonical?.canonical ?? null, variant: food.description, brand: null, imageUrl: null, aliases: canonical?.aliases ?? [], nutrients: usdaNutrients(food.foodNutrients ?? []), servings: [] }));
}
export async function searchOpenFoodFacts(query: string): Promise<NormalizedFood[]> {
  const url = new URL("https://world.openfoodfacts.org/cgi/search.pl"); url.search = new URLSearchParams({ search_terms: query, search_simple: "1", action: "process", json: "1", page_size: "10", fields: "code,product_name,product_name_es,brands,image_front_url,serving_size,nutriments" }).toString();
  const response = await fetch(url, { headers: { "User-Agent": "KYVO/0.1 (https://kyvo.app)" } }); if (!response.ok) throw new Error(`Open Food Facts search failed with ${response.status}`);
  const payload = await response.json() as { products?: OpenFoodFactsProduct[] };
  return (payload.products ?? []).flatMap((product) => { const sourceId = product.code?.trim(); const name = product.product_name_es?.trim() || product.product_name?.trim(); if (!sourceId || !name) return []; const nutrients = product.nutriments ?? {}; return [{ type: "commercial" as const, source: "open_food_facts" as const, sourceId, name, nameOriginal: product.product_name?.trim() || null, canonicalNameEs: null, variant: null, brand: product.brands?.trim() || null, imageUrl: product.image_front_url?.trim() || null, aliases: [], nutrients: { caloriesPer100g: numberOrNull(nutrients["energy-kcal_100g"]), proteinPer100g: numberOrNull(nutrients.proteins_100g), carbohydratesPer100g: numberOrNull(nutrients.carbohydrates_100g), fatPer100g: numberOrNull(nutrients.fat_100g), fiberPer100g: numberOrNull(nutrients.fiber_100g), sugarPer100g: numberOrNull(nutrients.sugars_100g), sodiumMgPer100g: toMilligrams(nutrients.sodium_100g) }, servings: gramsServing(product.serving_size) }]; });
}
function usdaNutrients(values: UsdaNutrient[]): Nutrients { const nutrients = emptyNutrients(); for (const nutrient of values) { const name = (nutrient.nutrientName ?? nutrient.nutrient?.name ?? "").toLowerCase(); const number = String(nutrient.nutrientNumber ?? nutrient.nutrient?.number ?? ""); const value = numberOrNull(nutrient.value ?? nutrient.amount); if (value === null) continue; if (number === "1008" || name === "energy") nutrients.caloriesPer100g = value; else if (number === "1003" || name === "protein") nutrients.proteinPer100g = value; else if (number === "1005" || name.includes("carbohydrate")) nutrients.carbohydratesPer100g = value; else if (number === "1004" || name.includes("total lipid") || name === "fat") nutrients.fatPer100g = value; else if (number === "1079" || name.includes("fiber")) nutrients.fiberPer100g = value; else if (number === "2000" || name.includes("sugars, total")) nutrients.sugarPer100g = value; else if (number === "1093" || name === "sodium, na") nutrients.sodiumMgPer100g = value; } return nutrients; }
function toMilligrams(value: unknown): number | null { const grams = numberOrNull(value); return grams === null ? null : grams * 1000; }
type UsdaFood = { fdcId: number; description: string; foodNutrients?: UsdaNutrient[] };
type UsdaNutrient = { nutrientName?: string; nutrientNumber?: string | number; value?: number; amount?: number; nutrient?: { name?: string; number?: string | number } };
type OpenFoodFactsProduct = { code?: string; product_name?: string; product_name_es?: string; brands?: string; image_front_url?: string; serving_size?: string; nutriments?: Record<string, unknown> };
